### ISSUE TITLE
CMake re-configuration fails in Windows

### ISSUE THREAD

**Issue by yuya-oc** [socketio/socket.io-client-cpp#70]
I'm using Visual Studio 2015.
At first time, CMake successfully configured and generated projects.
However, re-configuring fails after editing CMakeLists.txt.

```
1>------ ビルド開始: プロジェクト:ZERO_CHECK, 構成:Debug Win32 ------
1>  Checking Build System
1>  CMake is re-running because D:/Users/yuya-oc/git/socket.io-client-cpp/CMakeFiles/generate.stamp is out-of-date.
1>    the file 'D:/Users/yuya-oc/git/socket.io-client-cpp/CMakeLists.txt'
1>    is newer than 'D:/Users/yuya-oc/git/socket.io-client-cpp/CMakeFiles/generate.stamp.depend'
1>    result='-1'
1>  -- not define build type, set to release
1>  -- Boost version: 1.59.0
1>  -- Found the following Boost libraries:
1>  --   system
1>  --   date_time
1>  --   random
1>  CMake Error at CMakeLists.txt:82 (install):
1>    install FILES given directory "debug" to install.
1>
1>
1>  -- Configuring incomplete, errors occurred!
1>  See also "D:/Users/yuya-oc/git/socket.io-client-cpp/CMakeFiles/CMakeOutput.log".
1>  CMake Configure step failed.  Build files cannot be regenerated correctly.  Attempting to stop IDE build.
```

`Boost_LIBRARIES` contains `optimized/debug` keywords by `find_package()`. So I think that configuring fails.

```
# foreach(lib ${Boost_LIBRARIES})
#   message(${lib})
# endforeach()

optimized
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_system-vc140-mt-1_59.lib
debug
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_system-vc140-mt-gd-1_59.lib
optimized
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_date_time-vc140-mt-1_59.lib
debug
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_date_time-vc140-mt-gd-1_59.lib
optimized
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_random-vc140-mt-1_59.lib
debug
D:/Users/yuya-oc/src/boost_1_59_0/stage/lib/libboost_random-vc140-mt-gd-1_59.lib
```

**Comment by lawipac** [comment]
can you please advise on the way you generate proejcts?

I also use VC2015, but  got error:

```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/05/2016 1:13:57 AM.
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,71)" does not exist in the project, and will be ignored.
Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.28


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/05/2016 1:13:58 AM.
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,71)" does not exist in the project, and will be ignored.
Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj]
Done Building Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.28


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/05/2016 1:14:07 AM.
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,71)" does not exist in the project, and will be ignored.
Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.28


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags: 

The output was:
1
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/05/2016 1:14:07 AM.
The target "_ConvertPdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,37)" does not exist in the project, and will be ignored.
The target "_CollectPdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (34,70)" does not exist in the project, and will be ignored.
The target "_CollectMdbFiles" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,38)" does not exist in the project, and will be ignored.
The target "_CopyMdbFiles" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets (40,71)" does not exist in the project, and will be ignored.
Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /nologo /W0 /WX- /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc140.pdb" /Gd /TP /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj]
Done Building Project "C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1104: cannot open file 'ucrtd.lib' [C:\local\sio\CMakeFiles\3.5.2\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.28

```

**Comment by yuya-oc** [comment]
I'm sorry if misunderstanding, did you successfully install c/c++ compiler? In my memory, CMake tries to compile some c/c++ sources in order to check the compiler. But in your log, it seems that the the compiling failed. How about checking whether CMake correctly works?

JFYI, maybe I had used CMake 3.0 or 3.1.

**Comment by lawipac** [comment]
Thank you for your reply,  I did a clean install of VS2015 on a clean Win7sp1, with CMake 3.5.2 GUI tools, it can generate project files successfully.  As shown in below:

Boost environment variables are added using GUI tools.

![openssl_found](https://cloud.githubusercontent.com/assets/10069433/15538922/8e18dc3c-22c2-11e6-9506-9ecc1d29f767.png)

Generated projects are as follows:
![generated_projects](https://cloud.githubusercontent.com/assets/10069433/15538966/e54aa940-22c2-11e6-894e-6c1d09ef8b8d.png)

**Comment by lawipac** [comment]
However I have problems when compiling these VC projects.

Below is the error message when build sioclient.vcxproj

```
------ Build started: Project: sioclient, Configuration: Debug Win32 ------
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
  sio_client.cpp
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): error C2694: 'const char *websocketpp::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): note: see declaration of 'websocketpp::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): error C2694: 'const char *websocketpp::processor::error::processor_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): note: see declaration of 'websocketpp::processor::error::processor_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): error C2694: 'const char *websocketpp::transport::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): note: see declaration of 'websocketpp::transport::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): error C2694: 'const char *websocketpp::transport::iostream::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): note: see declaration of 'websocketpp::transport::iostream::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): error C2694: 'const char *websocketpp::extensions::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): note: see declaration of 'websocketpp::extensions::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): error C2694: 'const char *websocketpp::transport::asio::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): note: see declaration of 'websocketpp::transport::asio::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): error C2694: 'const char *websocketpp::transport::asio::socket::socket_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): note: see declaration of 'websocketpp::transport::asio::socket::socket_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
  sio_socket.cpp
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): error C2694: 'const char *websocketpp::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): note: see declaration of 'websocketpp::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): error C2694: 'const char *websocketpp::processor::error::processor_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): note: see declaration of 'websocketpp::processor::error::processor_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): error C2694: 'const char *websocketpp::transport::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): note: see declaration of 'websocketpp::transport::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): error C2694: 'const char *websocketpp::transport::iostream::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): note: see declaration of 'websocketpp::transport::iostream::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): error C2694: 'const char *websocketpp::extensions::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): note: see declaration of 'websocketpp::extensions::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): error C2694: 'const char *websocketpp::transport::asio::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): note: see declaration of 'websocketpp::transport::asio::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): error C2694: 'const char *websocketpp::transport::asio::socket::socket_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): note: see declaration of 'websocketpp::transport::asio::socket::socket_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
  sio_client_impl.cpp
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): error C2694: 'const char *websocketpp::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/error.hpp(151): note: see declaration of 'websocketpp::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): error C2694: 'const char *websocketpp::processor::error::processor_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/processors/base.hpp(165): note: see declaration of 'websocketpp::processor::error::processor_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): error C2694: 'const char *websocketpp::transport::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/base/connection.hpp(187): note: see declaration of 'websocketpp::transport::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): error C2694: 'const char *websocketpp::transport::iostream::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/iostream/base.hpp(77): note: see declaration of 'websocketpp::transport::iostream::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): error C2694: 'const char *websocketpp::extensions::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/extensions/extension.hpp(65): note: see declaration of 'websocketpp::extensions::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): error C2694: 'const char *websocketpp::transport::asio::error::category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/base.hpp(205): note: see declaration of 'websocketpp::transport::asio::error::category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): error C2694: 'const char *websocketpp::transport::asio::socket::socket_category::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
  C:\Users\a\socket.io-client-cpp\lib\websocketpp\websocketpp/transport/asio/security/base.hpp(107): note: see declaration of 'websocketpp::transport::asio::socket::socket_category::name'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\system_error(177): note: see declaration of 'std::error_category::name'
  sio_packet.cpp
  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by yuya-oc** [comment]
See http://stackoverflow.com/questions/32969289/error-in-websocketpp-library-and-boost-in-windows-visual-studio-2015 introduced in #81. You have to modify WEBSOCKETPP_NOEXCEPT definition in websocketpp. The latest websocketpp works well with VC2015, but I think this library uses an old one.

**Comment by lawipac** [comment]
Thank you for your pointer, I followed that, and successfully build CMake projects by updating [websocketapp](https://github.com/zaphoyd/websocketpp/commit/378437aecdcb1dfe62096ffd5d944bf1f640ccc3) to  version (https://github.com/zaphoyd/websocketpp/commit/378437aecdcb1dfe62096ffd5d944bf1f640ccc3)

**Comment by lawipac** [comment]
As to the issues you mentioned in top post, did you tried adding  -DCMAKE_BUILD_TYPE=Release to your CMake command line?

Looking at the output, it seems to be a Release vs Debug issue.

1>  -- not define build type, set to release
1>  CMake Error at CMakeLists.txt:82 (install):
...
1>    install FILES given directory "debug" to install.

**Comment by yuya-oc** [comment]
Maybe I didn't try that. Sure, it seems to be Release vs Debug issue, but I didn't sure why both of `debug` and `optimized` are included in `${Boost_LIBRARIES}`.
Unfortunately I'm not familiar with the combination of CMake and VC, so I don't know whether `${Boost_LIBRARIES}` is correct for VC.

**Comment by jmigual** [comment]
Hi, have there been any updates on this issue? The new versions of this library do not require CMake anymore

**Comment by jmigual** [comment]
Closing due to lack of reply
