### ISSUE TITLE
Suitable OpenSSL version for SocketIO client

### ISSUE THREAD

**Issue by rytisss** [socketio/socket.io-client-cpp#213]
Which version of OpenSSL is suitable for TLS client? I managed build it with boost 1.68.0 and OpenSSL  1.0.2g, but when I try to link client_tls lib, i am receiving a lot of errors:

In function `boost::asio::ssl::detail::openssl_init_base::instance()':
[build] sio_client.cpp:(.text._ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv[_ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv]+0xbd): undefined reference to `SSL_library_init'
[build] sio_client.cpp:(.text._ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv[_ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv]+0xc2): undefined reference to `SSL_load_error_strings'
[build] ................................
...............and so on

Build without TLS works well

**Comment by rytisss** [comment]
And which version of Boost is suitable?

**Comment by DraconPern** [comment]
using boost_1_63_0 with
`b2 asmflags=\safeseh runtime-link=static define=_BIND_TO_CURRENT_VCLIBS_VERSION=1 -j 4 stage`

**Comment by rytisss** [comment]
I seems like none of my Boost builds can't locate OpenSSL

**Comment by rytisss** [comment]
Ok, solved problem, when i was doing build of my project using CMake, pkgconfig was linking not right OpenSSL libs. I needed to link my own static build manually. TLS worked with boost 1.68.0 and OpenSSL 1.0.2p. Hope this will help other developers that encountered same problem :)
